// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package data

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createKey = `-- name: CreateKey :one
INSERT INTO api_keys (id, api_key, created_at, user_id)
VALUES ($1, $2, NOW(), $3)
RETURNING id, api_key, created_at, expires_at, user_id
`

type CreateKeyParams struct {
	ID     string    `json:"id"`
	ApiKey string    `json:"api_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createKey, arg.ID, arg.ApiKey, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM api_keys
WHERE user_id = $1
`

func (q *Queries) DeleteKey(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKey, userID)
	return err
}

const getKeyByID = `-- name: GetKeyByID :one
SELECT api_key
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetKeyByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getKeyByID, id)
	var api_key string
	err := row.Scan(&api_key)
	return api_key, err
}

const getKeyByUser = `-- name: GetKeyByUser :one
SELECT api_key, created_at
FROM api_keys
WHERE user_id = $1
`

type GetKeyByUserRow struct {
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetKeyByUser(ctx context.Context, userID uuid.UUID) (GetKeyByUserRow, error) {
	row := q.db.QueryRow(ctx, getKeyByUser, userID)
	var i GetKeyByUserRow
	err := row.Scan(&i.ApiKey, &i.CreatedAt)
	return i, err
}

const updateKey = `-- name: UpdateKey :exec
UPDATE api_keys SET
    id = $2,
    api_key = $3,
    created_at = NOW()
WHERE user_id = $1
`

type UpdateKeyParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     string    `json:"id"`
	ApiKey string    `json:"api_key"`
}

func (q *Queries) UpdateKey(ctx context.Context, arg UpdateKeyParams) error {
	_, err := q.db.Exec(ctx, updateKey, arg.UserID, arg.ID, arg.ApiKey)
	return err
}
