// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changes.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const addFeaturesChange = `-- name: AddFeaturesChange :exec
INSERT INTO features_changes (id, user_id, change_type, name, description, category)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddFeaturesChangeParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ChangeType  string    `json:"change_type"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

func (q *Queries) AddFeaturesChange(ctx context.Context, arg AddFeaturesChangeParams) error {
	_, err := q.db.Exec(ctx, addFeaturesChange,
		arg.ID,
		arg.UserID,
		arg.ChangeType,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	return err
}

const addGamesChange = `-- name: AddGamesChange :exec
INSERT INTO games_changes (id, user_id, change_type, title, developer, publisher, release_year, platforms, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddGamesChangeParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ChangeType  string    `json:"change_type"`
	Title       string    `json:"title"`
	Developer   *string   `json:"developer"`
	Publisher   *string   `json:"publisher"`
	ReleaseYear *int32    `json:"release_year"`
	Platforms   []string  `json:"platforms"`
	Description *string   `json:"description"`
}

func (q *Queries) AddGamesChange(ctx context.Context, arg AddGamesChangeParams) error {
	_, err := q.db.Exec(ctx, addGamesChange,
		arg.ID,
		arg.UserID,
		arg.ChangeType,
		arg.Title,
		arg.Developer,
		arg.Publisher,
		arg.ReleaseYear,
		arg.Platforms,
		arg.Description,
	)
	return err
}

const addGamesFeaturesChange = `-- name: AddGamesFeaturesChange :exec
INSERT INTO games_features_changes (id, user_id, change_type, game_id, feature_id, notes, verified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AddGamesFeaturesChangeParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ChangeType string    `json:"change_type"`
	GameID     uuid.UUID `json:"game_id"`
	FeatureID  uuid.UUID `json:"feature_id"`
	Notes      *string   `json:"notes"`
	Verified   bool      `json:"verified"`
}

func (q *Queries) AddGamesFeaturesChange(ctx context.Context, arg AddGamesFeaturesChangeParams) error {
	_, err := q.db.Exec(ctx, addGamesFeaturesChange,
		arg.ID,
		arg.UserID,
		arg.ChangeType,
		arg.GameID,
		arg.FeatureID,
		arg.Notes,
		arg.Verified,
	)
	return err
}

const getFeaturesChangeByID = `-- name: GetFeaturesChangeByID :one
SELECT id, created_at, status, change_type, user_id, moderator_id, name, description, category FROM features_changes
WHERE id = $1
`

func (q *Queries) GetFeaturesChangeByID(ctx context.Context, id uuid.UUID) (FeaturesChange, error) {
	row := q.db.QueryRow(ctx, getFeaturesChangeByID, id)
	var i FeaturesChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.ChangeType,
		&i.UserID,
		&i.ModeratorID,
		&i.Name,
		&i.Description,
		&i.Category,
	)
	return i, err
}

const getFeaturesChanges = `-- name: GetFeaturesChanges :many
SELECT id, created_at, status, change_type, user_id, moderator_id, name, description, category FROM features_changes
ORDER BY category DESC
LIMIT $1
`

func (q *Queries) GetFeaturesChanges(ctx context.Context, limit int32) ([]FeaturesChange, error) {
	rows, err := q.db.Query(ctx, getFeaturesChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeaturesChange
	for rows.Next() {
		var i FeaturesChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.ChangeType,
			&i.UserID,
			&i.ModeratorID,
			&i.Name,
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesChangeByID = `-- name: GetGamesChangeByID :one
SELECT id, created_at, status, change_type, user_id, moderator_id, title, developer, publisher, release_year, platforms, description FROM games_changes
WHERE id = $1
`

func (q *Queries) GetGamesChangeByID(ctx context.Context, id uuid.UUID) (GamesChange, error) {
	row := q.db.QueryRow(ctx, getGamesChangeByID, id)
	var i GamesChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.ChangeType,
		&i.UserID,
		&i.ModeratorID,
		&i.Title,
		&i.Developer,
		&i.Publisher,
		&i.ReleaseYear,
		&i.Platforms,
		&i.Description,
	)
	return i, err
}

const getGamesChanges = `-- name: GetGamesChanges :many
SELECT id, created_at, status, change_type, user_id, moderator_id, title, developer, publisher, release_year, platforms, description FROM games_changes
ORDER BY title
LIMIT $1
`

func (q *Queries) GetGamesChanges(ctx context.Context, limit int32) ([]GamesChange, error) {
	rows, err := q.db.Query(ctx, getGamesChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamesChange
	for rows.Next() {
		var i GamesChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.ChangeType,
			&i.UserID,
			&i.ModeratorID,
			&i.Title,
			&i.Developer,
			&i.Publisher,
			&i.ReleaseYear,
			&i.Platforms,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesFeaturesChangeByID = `-- name: GetGamesFeaturesChangeByID :one
SELECT id, created_at, status, change_type, user_id, moderator_id, game_id, feature_id, notes, verified FROM games_features_changes
WHERE id = $1
`

func (q *Queries) GetGamesFeaturesChangeByID(ctx context.Context, id uuid.UUID) (GamesFeaturesChange, error) {
	row := q.db.QueryRow(ctx, getGamesFeaturesChangeByID, id)
	var i GamesFeaturesChange
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Status,
		&i.ChangeType,
		&i.UserID,
		&i.ModeratorID,
		&i.GameID,
		&i.FeatureID,
		&i.Notes,
		&i.Verified,
	)
	return i, err
}

const getGamesFeaturesChanges = `-- name: GetGamesFeaturesChanges :many
SELECT id, created_at, status, change_type, user_id, moderator_id, game_id, feature_id, notes, verified FROM games_features_changes
LIMIT $1
`

func (q *Queries) GetGamesFeaturesChanges(ctx context.Context, limit int32) ([]GamesFeaturesChange, error) {
	rows, err := q.db.Query(ctx, getGamesFeaturesChanges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamesFeaturesChange
	for rows.Next() {
		var i GamesFeaturesChange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.ChangeType,
			&i.UserID,
			&i.ModeratorID,
			&i.GameID,
			&i.FeatureID,
			&i.Notes,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitFeaturesChange = `-- name: SubmitFeaturesChange :exec
INSERT INTO features (id, name, description, category, slug)
SELECT 
    features_changes.id, 
    features_changes.name, 
    features_changes.description, 
    features_changes.category, 
    LOWER(REPLACE(CONCAT(features_changes.name, '-', features_changes.category), ' ', '-'))
FROM features_changes
WHERE features_changes.id = $1
ON CONFLICT (slug) DO NOTHING
`

func (q *Queries) SubmitFeaturesChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, submitFeaturesChange, id)
	return err
}

const submitGamesChange = `-- name: SubmitGamesChange :exec
INSERT INTO games (id, title, developer, publisher, release_year, platforms, description, slug)
SELECT 
    games_changes.id, 
    games_changes.title, 
    games_changes.developer, 
    games_changes.publisher, 
    games_changes.release_year, 
    games_changes.platforms, 
    games_changes.description, 
    LOWER(REPLACE(CONCAT(games_changes.title, '-', games_changes.developer), ' ', '-'))
FROM games_changes
WHERE games_changes.id = $1
ON CONFLICT (slug) DO NOTHING
`

func (q *Queries) SubmitGamesChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, submitGamesChange, id)
	return err
}

const submitGamesFeaturesChange = `-- name: SubmitGamesFeaturesChange :exec
INSERT INTO games_features (id, updated_at, game_id, feature_id, notes, verified)
SELECT 
    games_features_changes.id,
    NOW(),
    games_features_changes.game_id,
    games_features_changes.feature_id, 
    games_features_changes.notes, 
    games_features_changes.verified
FROM games_features_changes
WHERE games_features_changes.id = $1
`

func (q *Queries) SubmitGamesFeaturesChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, submitGamesFeaturesChange, id)
	return err
}

const updateFeaturesChange = `-- name: UpdateFeaturesChange :exec
UPDATE features_changes SET 
    status = $2,
    moderator_id = $3
WHERE id = $1
`

type UpdateFeaturesChangeParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) UpdateFeaturesChange(ctx context.Context, arg UpdateFeaturesChangeParams) error {
	_, err := q.db.Exec(ctx, updateFeaturesChange, arg.ID, arg.Status, arg.ModeratorID)
	return err
}

const updateGamesChange = `-- name: UpdateGamesChange :exec
UPDATE games_changes SET 
    status = $2,
    moderator_id = $3
WHERE id = $1
`

type UpdateGamesChangeParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) UpdateGamesChange(ctx context.Context, arg UpdateGamesChangeParams) error {
	_, err := q.db.Exec(ctx, updateGamesChange, arg.ID, arg.Status, arg.ModeratorID)
	return err
}

const updateGamesFeaturesChange = `-- name: UpdateGamesFeaturesChange :exec
UPDATE games_features_changes SET 
    status = $2,
    moderator_id = $3
WHERE id = $1
`

type UpdateGamesFeaturesChangeParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) UpdateGamesFeaturesChange(ctx context.Context, arg UpdateGamesFeaturesChangeParams) error {
	_, err := q.db.Exec(ctx, updateGamesFeaturesChange, arg.ID, arg.Status, arg.ModeratorID)
	return err
}
