// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const addFeature = `-- name: AddFeature :one
INSERT INTO features (created_at, updated_at, name, description, category, slug)
VALUES (NOW(), NOW(), $1, $2, $3, LOWER(REPLACE(CONCAT($1::text, '-', $3::text), ' ', '-')))
ON CONFLICT (slug) DO NOTHING
RETURNING id, created_at, updated_at, name, description, category, slug
`

type AddFeatureParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Category    string  `json:"category"`
}

func (q *Queries) AddFeature(ctx context.Context, arg AddFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, addFeature, arg.Name, arg.Description, arg.Category)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Slug,
	)
	return i, err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features
WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const getFeature = `-- name: GetFeature :one
SELECT id, name, description, category FROM features
WHERE id = $1
`

type GetFeatureRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

func (q *Queries) GetFeature(ctx context.Context, id uuid.UUID) (GetFeatureRow, error) {
	row := q.db.QueryRow(ctx, getFeature, id)
	var i GetFeatureRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
	)
	return i, err
}

const getFeatures = `-- name: GetFeatures :many
SELECT id, name, description, category 
FROM features
ORDER BY category DESC
LIMIT $1
`

type GetFeaturesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

func (q *Queries) GetFeatures(ctx context.Context, limit int32) ([]GetFeaturesRow, error) {
	rows, err := q.db.Query(ctx, getFeatures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturesRow
	for rows.Next() {
		var i GetFeaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturesSearch = `-- name: GetFeaturesSearch :many
SELECT id, name, description, category 
FROM features
WHERE 
    name ILIKE CONCAT('%', $1::text, '%')
    OR category ILIKE CONCAT('%', $1::text, '%')
ORDER BY category DESC
`

type GetFeaturesSearchRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

func (q *Queries) GetFeaturesSearch(ctx context.Context, dollar_1 string) ([]GetFeaturesSearchRow, error) {
	rows, err := q.db.Query(ctx, getFeaturesSearch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturesSearchRow
	for rows.Next() {
		var i GetFeaturesSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeature = `-- name: UpdateFeature :exec
UPDATE features SET 
    updated_at = NOW(),
    name = $2,
    description = $3,
    category = $4
WHERE id = $1
`

type UpdateFeatureParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

func (q *Queries) UpdateFeature(ctx context.Context, arg UpdateFeatureParams) error {
	_, err := q.db.Exec(ctx, updateFeature,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	return err
}
