// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games_features.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGameFeature = `-- name: CreateGameFeature :one
INSERT INTO games_features (created_at, updated_at, game_id, feature_id, notes, verified)
VALUES (NOW(), NOW(), $1, $2, $3, $4)
RETURNING id, created_at, updated_at, game_id, feature_id, notes, verified
`

type CreateGameFeatureParams struct {
	GameID    uuid.UUID   `json:"game_id"`
	FeatureID uuid.UUID   `json:"feature_id"`
	Notes     pgtype.Text `json:"notes"`
	Verified  bool        `json:"verified"`
}

func (q *Queries) CreateGameFeature(ctx context.Context, arg CreateGameFeatureParams) (GamesFeature, error) {
	row := q.db.QueryRow(ctx, createGameFeature,
		arg.GameID,
		arg.FeatureID,
		arg.Notes,
		arg.Verified,
	)
	var i GamesFeature
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GameID,
		&i.FeatureID,
		&i.Notes,
		&i.Verified,
	)
	return i, err
}

const deleteGameFeature = `-- name: DeleteGameFeature :exec
DELETE FROM games_features
WHERE game_id = $1 AND feature_id = $2
`

type DeleteGameFeatureParams struct {
	GameID    uuid.UUID `json:"game_id"`
	FeatureID uuid.UUID `json:"feature_id"`
}

func (q *Queries) DeleteGameFeature(ctx context.Context, arg DeleteGameFeatureParams) error {
	_, err := q.db.Exec(ctx, deleteGameFeature, arg.GameID, arg.FeatureID)
	return err
}

const getFeaturesByGame = `-- name: GetFeaturesByGame :many
SELECT 
    games_features.id, games_features.notes, games_features.verified,
    features.id AS feature_id, features.name, features.description, features.category
FROM games_features
INNER JOIN features ON games_features.feature_id = features.id
WHERE games_features.game_id = $1
`

type GetFeaturesByGameRow struct {
	ID          uuid.UUID   `json:"id"`
	Notes       pgtype.Text `json:"notes"`
	Verified    bool        `json:"verified"`
	FeatureID   uuid.UUID   `json:"feature_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Category    string      `json:"category"`
}

func (q *Queries) GetFeaturesByGame(ctx context.Context, gameID uuid.UUID) ([]GetFeaturesByGameRow, error) {
	rows, err := q.db.Query(ctx, getFeaturesByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturesByGameRow
	for rows.Next() {
		var i GetFeaturesByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.Notes,
			&i.Verified,
			&i.FeatureID,
			&i.Name,
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameFeature = `-- name: GetGameFeature :one
SELECT
    games_features.notes, games_features.verified,
    games.title,
    features.name
FROM games_features
JOIN games ON games_features.game_id = games.id
JOIN features ON games_features.feature_id = features.id
WHERE games_features.game_id = $1 AND games_features.feature_id = $2
`

type GetGameFeatureParams struct {
	GameID    uuid.UUID `json:"game_id"`
	FeatureID uuid.UUID `json:"feature_id"`
}

type GetGameFeatureRow struct {
	Notes    pgtype.Text `json:"notes"`
	Verified bool        `json:"verified"`
	Title    string      `json:"title"`
	Name     string      `json:"name"`
}

func (q *Queries) GetGameFeature(ctx context.Context, arg GetGameFeatureParams) (GetGameFeatureRow, error) {
	row := q.db.QueryRow(ctx, getGameFeature, arg.GameID, arg.FeatureID)
	var i GetGameFeatureRow
	err := row.Scan(
		&i.Notes,
		&i.Verified,
		&i.Title,
		&i.Name,
	)
	return i, err
}

const getGamesByFeature = `-- name: GetGamesByFeature :many
SELECT 
    games_features.notes, games_features.verified,
    games.id AS game_id, games.title, games.developer, games.publisher, games.release_year, games.platforms, games.description
FROM games_features
INNER JOIN games ON games_features.game_id = games.id
WHERE games_features.feature_id = $1
`

type GetGamesByFeatureRow struct {
	Notes       pgtype.Text `json:"notes"`
	Verified    bool        `json:"verified"`
	GameID      uuid.UUID   `json:"game_id"`
	Title       string      `json:"title"`
	Developer   pgtype.Text `json:"developer"`
	Publisher   pgtype.Text `json:"publisher"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	Platforms   []string    `json:"platforms"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetGamesByFeature(ctx context.Context, featureID uuid.UUID) ([]GetGamesByFeatureRow, error) {
	rows, err := q.db.Query(ctx, getGamesByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesByFeatureRow
	for rows.Next() {
		var i GetGamesByFeatureRow
		if err := rows.Scan(
			&i.Notes,
			&i.Verified,
			&i.GameID,
			&i.Title,
			&i.Developer,
			&i.Publisher,
			&i.ReleaseYear,
			&i.Platforms,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameFeature = `-- name: UpdateGameFeature :exec
UPDATE games_features SET
    updated_at = NOW(),
    game_id = $3,
    feature_id = $4,
    notes = $5,
    verified = $6
WHERE game_id = $1 AND feature_id = $2
`

type UpdateGameFeatureParams struct {
	GameID      uuid.UUID   `json:"game_id"`
	FeatureID   uuid.UUID   `json:"feature_id"`
	GameID_2    uuid.UUID   `json:"game_id_2"`
	FeatureID_2 uuid.UUID   `json:"feature_id_2"`
	Notes       pgtype.Text `json:"notes"`
	Verified    bool        `json:"verified"`
}

func (q *Queries) UpdateGameFeature(ctx context.Context, arg UpdateGameFeatureParams) error {
	_, err := q.db.Exec(ctx, updateGameFeature,
		arg.GameID,
		arg.FeatureID,
		arg.GameID_2,
		arg.FeatureID_2,
		arg.Notes,
		arg.Verified,
	)
	return err
}
