// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGame = `-- name: AddGame :one
INSERT INTO games (created_at, updated_at, title, developer, publisher, release_year, platforms, description, slug)
VALUES (NOW(), NOW(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO NOTHING
RETURNING id, created_at, updated_at, title, developer, publisher, release_year, platforms, description, slug
`

type AddGameParams struct {
	Title       string      `json:"title"`
	Developer   pgtype.Text `json:"developer"`
	Publisher   pgtype.Text `json:"publisher"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	Platforms   []string    `json:"platforms"`
	Description pgtype.Text `json:"description"`
	Slug        pgtype.Text `json:"slug"`
}

func (q *Queries) AddGame(ctx context.Context, arg AddGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, addGame,
		arg.Title,
		arg.Developer,
		arg.Publisher,
		arg.ReleaseYear,
		arg.Platforms,
		arg.Description,
		arg.Slug,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Developer,
		&i.Publisher,
		&i.ReleaseYear,
		&i.Platforms,
		&i.Description,
		&i.Slug,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, title, developer, publisher, release_year, platforms, description FROM games
WHERE id = $1
`

type GetGameRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Developer   pgtype.Text `json:"developer"`
	Publisher   pgtype.Text `json:"publisher"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	Platforms   []string    `json:"platforms"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (GetGameRow, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Developer,
		&i.Publisher,
		&i.ReleaseYear,
		&i.Platforms,
		&i.Description,
	)
	return i, err
}

const getGames = `-- name: GetGames :many
SELECT id, title, developer, publisher, release_year, platforms, description
FROM games
ORDER BY title
`

type GetGamesRow struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Developer   pgtype.Text `json:"developer"`
	Publisher   pgtype.Text `json:"publisher"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	Platforms   []string    `json:"platforms"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) GetGames(ctx context.Context) ([]GetGamesRow, error) {
	rows, err := q.db.Query(ctx, getGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesRow
	for rows.Next() {
		var i GetGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Developer,
			&i.Publisher,
			&i.ReleaseYear,
			&i.Platforms,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesWithFeatures = `-- name: GetGamesWithFeatures :many
SELECT 
    games.id,
    games.title,
    games.developer,
    games.publisher,
    games.release_year,
    games.platforms,
    games.description,
    (
        SELECT json_agg(json_build_object('id', features.id, 'name', features.name, 'title', games.title, 'notes', games_features.notes, 'verified', games_features.verified))
        FROM games_features
        JOIN features ON features.id = games_features.feature_id
        WHERE games_features.game_id = games.id
    ) AS game_features
FROM games
ORDER BY games.title
`

type GetGamesWithFeaturesRow struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Developer    pgtype.Text `json:"developer"`
	Publisher    pgtype.Text `json:"publisher"`
	ReleaseYear  pgtype.Int4 `json:"release_year"`
	Platforms    []string    `json:"platforms"`
	Description  pgtype.Text `json:"description"`
	GameFeatures []byte      `json:"game_features"`
}

func (q *Queries) GetGamesWithFeatures(ctx context.Context) ([]GetGamesWithFeaturesRow, error) {
	rows, err := q.db.Query(ctx, getGamesWithFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesWithFeaturesRow
	for rows.Next() {
		var i GetGamesWithFeaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Developer,
			&i.Publisher,
			&i.ReleaseYear,
			&i.Platforms,
			&i.Description,
			&i.GameFeatures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games SET 
    updated_at = NOW(),
    title = $2,
    developer = $3,
    publisher = $4,
    release_year = $5,
    platforms = $6,
    description = $7
WHERE id = $1
`

type UpdateGameParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Developer   pgtype.Text `json:"developer"`
	Publisher   pgtype.Text `json:"publisher"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	Platforms   []string    `json:"platforms"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.Exec(ctx, updateGame,
		arg.ID,
		arg.Title,
		arg.Developer,
		arg.Publisher,
		arg.ReleaseYear,
		arg.Platforms,
		arg.Description,
	)
	return err
}
