// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string           `json:"id"`
	ApiKey    string           `json:"api_key"`
	CreatedAt time.Time        `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    uuid.UUID        `json:"user_id"`
}

type Feature struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
	Slug        *string   `json:"slug"`
}

type FeaturesChange struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Status      string    `json:"status"`
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
}

type Game struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Title       string    `json:"title"`
	Developer   *string   `json:"developer"`
	Publisher   *string   `json:"publisher"`
	ReleaseYear *int32    `json:"release_year"`
	Platforms   []string  `json:"platforms"`
	Description *string   `json:"description"`
	Slug        *string   `json:"slug"`
}

type GamesChange struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Status      string    `json:"status"`
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
	Title       string    `json:"title"`
	Developer   *string   `json:"developer"`
	Publisher   *string   `json:"publisher"`
	ReleaseYear *int32    `json:"release_year"`
	Platforms   []string  `json:"platforms"`
	Description *string   `json:"description"`
}

type GamesFeature struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	GameID    uuid.UUID `json:"game_id"`
	FeatureID uuid.UUID `json:"feature_id"`
	Notes     *string   `json:"notes"`
	Verified  bool      `json:"verified"`
}

type GamesFeaturesChange struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Status      string    `json:"status"`
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
	GameID      uuid.UUID `json:"game_id"`
	FeatureID   uuid.UUID `json:"feature_id"`
	Notes       *string   `json:"notes"`
	Verified    bool      `json:"verified"`
}

type Mod struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	GameID      uuid.UUID `json:"game_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SourceUrl   string    `json:"source_url"`
	Verified    bool      `json:"verified"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      string    `json:"role"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
}
