// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"time"

	"github.com/google/uuid"
)

type Feature struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Category    string    `json:"category"`
	Slug        *string   `json:"slug"`
}

type Game struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Title       string    `json:"title"`
	Developer   *string   `json:"developer"`
	Publisher   *string   `json:"publisher"`
	ReleaseYear *int32    `json:"release_year"`
	Platforms   []string  `json:"platforms"`
	Description *string   `json:"description"`
	Slug        *string   `json:"slug"`
}

type GamesFeature struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	GameID    uuid.UUID `json:"game_id"`
	FeatureID uuid.UUID `json:"feature_id"`
	Notes     *string   `json:"notes"`
	Verified  bool      `json:"verified"`
}

type Mod struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	GameID      uuid.UUID `json:"game_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SourceUrl   string    `json:"source_url"`
	Verified    bool      `json:"verified"`
}
